### ISSUE TITLE
Question about separate object prediction

### ISSUE THREAD

**Issue by ASMIftekhar** [DirtyHarryLYL/SymNet#2]
Thanks for your wonderful work. 
As I understood in inference for detecting objects you guys are using a separate dedicatedly trained object detector. But your main model contains an object detector related to loss, L<sub>cls</sub>. 
Is there any reason to use a separate object detector's predictions?

**Comment by silicx** [comment]
The main purpose of separate object classifier is to facilitate our hyper-parameter tuning and evaluation, since it is basically independent from the main structure. It is equivalent to combine the two parts together but may need different parameters. Thank you for pointing this out and we'll consider to provide one-stage models.

**Comment by ASMIftekhar** [comment]
It would be interesting to see the results from one single model. Thanks
